# use python 180123060_Jatin_q1.py to run this code

import matplotlib.pyplot as plt
import random

values= []		#store the random value generated by algorithm
p= 0.0002       # probability of every sigle element of set 

for i in range(100000):
    u= random.random()
    values.append((int(u/p))*2 + 1)

plt.hist(values, bins = 1000, rwidth = 0.5)
plt.xlabel('Discrete Variables',size= 20)
plt.ylabel('Frequemcy',size= 20)
plt.title('Generating Discrete Variables',size= 20)
plt.show()
  
  
